services:
  postgres:
    image: postgres
    restart: always
    container_name: task-api-teste-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: task-api-teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
