### create task 1
POST http://localhost:3000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMTU1Nzk4LCJleHAiOjE3MjMxNTkzOTh9.nl9i_RHDMWJgu6oO8HIveT1toP3fE-d_JjsbvpbqlQ8

{
    "title": "titulo 4",
    "description": "descrição",
    "expirationDate": "2024-08-08"
}

### create task 2
POST http://localhost:3000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMTYwMjY1LCJleHAiOjE3MjMxNjM4NjV9.vAeKM-gBUMj-S8Hg14fd7hFBvvks-ASfahteH8BXgR8

{
    "title": "titulo 5",
    "description": "descrição 3",
    "expirationDate": "2024-01-01"
}

### find id
GET http://localhost:3000/task/e0881f1b-cca9-4087-86df-6acfecbdb66f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMTYwMjY1LCJleHAiOjE3MjMxNjM4NjV9.vAeKM-gBUMj-S8Hg14fd7hFBvvks-ASfahteH8BXgR8

### find all
GET http://localhost:3000/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMjQwMDg4LCJleHAiOjE3MjMyNDM2ODh9.Ciww6XfG3r0gxKXJz_q-XcEytiOyDPUI8WBheKN_2d8

### find filter
GET http://localhost:3000/task?status=TO_DO&task?title=titulo 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMjQwMDg4LCJleHAiOjE3MjMyNDM2ODh9.Ciww6XfG3r0gxKXJz_q-XcEytiOyDPUI8WBheKN_2d8

### update
PUT http://localhost:3000/task/ff7bb843-f9f7-46ad-8b63-05b9384000e1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMjQwMDg4LCJleHAiOjE3MjMyNDM2ODh9.Ciww6XfG3r0gxKXJz_q-XcEytiOyDPUI8WBheKN_2d8

{
    "title": "alterado sem o status",
    "description": "descriok",
    "status": "IN_PROGRESS",
    "expirationDate": "2024-02-01"
}

### delete
DELETE http://localhost:3000/task/e0881f1b-cca9-4087-86df-6acfecbdb66f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNjI5YjdlMS01ZWQ4LTQyMjktYjJlZC00YmY2YWM2OGM4MTgiLCJ1c2VybmFtZSI6ImV1IiwiaWF0IjoxNzIzMjQwMDg4LCJleHAiOjE3MjMyNDM2ODh9.Ciww6XfG3r0gxKXJz_q-XcEytiOyDPUI8WBheKN_2d8